name: Release
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          compiler: pdflatex
#           latexmk_use_xelatex: true
          args: -jobname=Algebraic-curves-courcework -synctex=1 -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          post_compile: "latexmk -c"
          # extra_fonts: ./resources/fonts/*.ttf
      - uses: actions/upload-artifact@v3
        with:
          name: Algebraic-curves-courcework
          path: ./Algebraic-curves-courcework.pdf

  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Algebraic-curves-courcework
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "Algebraic-curves-courcework.pdf"
#           bodyFile: "body.md"
